pipeline {
    //agent any
    agent {
        label {
            label ""
            customWorkspace "/Users/chirag.verma/Desktop/qa-end-to-end"
        }
    }

    environment {
        APPIUM_PORT_ONE= 4723
        APPIUM_PORT_TWO= 4724
    }

  tools {nodejs "node"}

  stages {
        stage('Checkout Shopfloor App') {
            steps {
                dir("/Users/chirag.verma/Desktop/sfa") {
                echo "Building.."
                //sh 'git reset --hard HEAD'
                //sh 'git clean -f -d'
                //sh 'git pull git@gitlab.fftech.info:mobile/ios/sof/sfa.git'
                }
                
            }
        }
        
        stage('Checkout Consumer App') {
            steps {
                dir("/Users/chirag.verma/Desktop/sof-consumer-app") {
                echo "Building.."
                sh 'git reset --hard HEAD'
                sh 'git clean -f -d'
                sh 'git pull git@gitlab.fftech.info:mobile/ios/sof/sof-consumer-app.git'
                }
            }
        }
        
        stage('Checkout Mirror') {
            steps {
                dir("/Users/chirag.verma/Desktop/mirror/") {
                //sh 'git reset --hard HEAD'
                //sh 'git clean -f -d'
                //sh 'git pull git@gitlab.fftech.info:sof/mirror.git'
            }
            }
        }
        
        stage('Checkout End to End Tests') {
            steps {
                dir("/Users/chirag.verma/Desktop/qa-end-to-end/") {
                //sh 'git reset --hard HEAD'
                //sh 'git clean -f -d'
                //sh 'git pull git@gitlab.fftech.info:sof/qa-end-to-end.git'
            }
                    
            }
        }

        stage('Starting Appium Servers') {
            steps {
                parallel(
                    ServerOne: {
                    echo "Starting Appium Server 1"
                  },
                    ServerTwo: {
                    echo "Starting Appium Server 2"
                  })
                  }
              }

          stage('Starting End to End Tests') {
            steps {
                echo "Starting End to End Tests"
                dir("/Users/chirag.verma/Desktop/qa-end-to-end/") {
                sh './tests.sh'
                echo "Shutting Down Appium Servers"
            }
          }
        }
        
        stage('Reports') {
            steps {
            script {
            allure([
                    includeProperties: false,
                    jdk: '',
                    properties: [],
                    reportBuildPolicy: 'ALWAYS',
                    results: [[path: 'target/allure-results']]
         ])
    }
    }
}
            

    }
}  